<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <PackAsTool>true</PackAsTool>
        <PackageId>Gman.Cucumber.Cannery</PackageId>
        <ToolCommandName>cucumber-cannery</ToolCommandName>
        <PackageOutputPath>./nupkg</PackageOutputPath>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Description>Documentation generator for cucumber / ReqnRoll libraries</Description>
        <RepositoryUrl>https://github.com/gman-au/cucumber-cannery</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cucumber.Cannery.Application\Cucumber.Cannery.Application.csproj" />
        <ProjectReference Include="..\Cucumber.Cannery.Infrastructure.AssemblyLoad\Cucumber.Cannery.Infrastructure.AssemblyLoad.csproj" />
        <ProjectReference Include="..\Cucumber.Cannery.Infrastructure.Io\Cucumber.Cannery.Infrastructure.Io.csproj" />
        <ProjectReference Include="..\Cucumber.Cannery.Infrastructure.Markdown\Cucumber.Cannery.Infrastructure.Markdown.csproj" />
        <ProjectReference Include="..\Cucumber.Cannery.Infrastructure.Parsing\Cucumber.Cannery.Infrastructure.Parsing.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.6" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.6" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.6" />
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.6" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="nupkg\" />
    </ItemGroup>

</Project>
